execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest20] at @s run tag @e[tag=body,r=1] add destreset
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest20] at @s run tag @e[tag=body,r=1] remove dest20
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest20] at @s run tag @s add destreset
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest20] at @s run tag @s remove dest20
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest19] at @s run tag @e[tag=body,r=1] add dest20
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest19] at @s run tag @e[tag=body,r=1] remove dest19
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest19] at @s run tag @s add dest20
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest19] at @s run tag @s remove dest19
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest18] at @s run tag @e[tag=body,r=1] add dest19
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest18] at @s run tag @e[tag=body,r=1] remove dest18
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest18] at @s run tag @s add dest19
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest18] at @s run tag @s remove dest18
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest17] at @s run tag @e[tag=body,r=1] add dest18
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest17] at @s run tag @e[tag=body,r=1] remove dest17
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest17] at @s run tag @s add dest18
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest17] at @s run tag @s remove dest17
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest16] at @s run tag @e[tag=body,r=1] add dest17
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest16] at @s run tag @e[tag=body,r=1] remove dest16
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest16] at @s run tag @s add dest17
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest16] at @s run tag @s remove dest16
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest15] at @s run tag @e[tag=body,r=1] add dest16
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest15] at @s run tag @e[tag=body,r=1] remove dest15
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest15] at @s run tag @s add dest16
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest15] at @s run tag @s remove dest15
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest14] at @s run tag @e[tag=body,r=1] add dest15
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest14] at @s run tag @e[tag=body,r=1] remove dest14
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest14] at @s run tag @s add dest15
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest14] at @s run tag @s remove dest14
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest13] at @s run tag @e[tag=body,r=1] add dest14
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest13] at @s run tag @e[tag=body,r=1] remove dest13
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest13] at @s run tag @s add dest14
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest13] at @s run tag @s remove dest13
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest12] at @s run tag @e[tag=body,r=1] add dest13
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest12] at @s run tag @e[tag=body,r=1] remove dest12
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest12] at @s run tag @s add dest13
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest12] at @s run tag @s remove dest12
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest11] at @s run tag @e[tag=body,r=1] add dest12
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest11] at @s run tag @e[tag=body,r=1] remove dest11
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest11] at @s run tag @s add dest12
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest11] at @s run tag @s remove dest11
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest10] at @s run tag @e[tag=body,r=1] add dest11
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest10] at @s run tag @e[tag=body,r=1] remove dest10
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest10] at @s run tag @s add dest11
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest10] at @s run tag @s remove dest10
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest9] at @s run tag @e[tag=body,r=1] add dest10
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest9] at @s run tag @e[tag=body,r=1] remove dest9
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest9] at @s run tag @s add dest10
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest9] at @s run tag @s remove dest9
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest8] at @s run tag @e[tag=body,r=1] add dest9
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest8] at @s run tag @e[tag=body,r=1] remove dest8
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest8] at @s run tag @s add dest9
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest8] at @s run tag @s remove dest8
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest7] at @s run tag @e[tag=body,r=1] add dest8
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest7] at @s run tag @e[tag=body,r=1] remove dest7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest7] at @s run tag @s add dest8
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest7] at @s run tag @s remove dest7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest6] at @s run tag @e[tag=body,r=1] add dest7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest6] at @s run tag @e[tag=body,r=1] remove dest6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest6] at @s run tag @s add dest7
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest6] at @s run tag @s remove dest6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest5] at @s run tag @e[tag=body,r=1] add dest6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest5] at @s run tag @e[tag=body,r=1] remove dest5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest5] at @s run tag @s add dest6
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest5] at @s run tag @s remove dest5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest4] at @s run tag @e[tag=body,r=1] add dest5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest4] at @s run tag @e[tag=body,r=1] remove dest4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest4] at @s run tag @s add dest5
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest4] at @s run tag @s remove dest4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest3] at @s run tag @e[tag=body,r=1] add dest4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest3] at @s run tag @e[tag=body,r=1] remove dest3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest3] at @s run tag @s add dest4
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest3] at @s run tag @s remove dest3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest2] at @s run tag @e[tag=body,r=1] add dest3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest2] at @s run tag @e[tag=body,r=1] remove dest2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest2] at @s run tag @s add dest3
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest2] at @s run tag @s remove dest2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest1] at @s run tag @e[tag=body,r=1] add dest2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest1] at @s run tag @e[tag=body,r=1] remove dest1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest1] at @s run tag @s add dest2
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=dest1] at @s run tag @s remove dest1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=destreset] at @s run tag @e[tag=body,r=1] add dest1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=destreset] at @s run tag @e[tag=body,r=1] remove destreset
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=destreset] at @s run tag @s add dest1
execute as @e[type=tcmb:tcmb_car,c=1] at @s run execute as @s[tag=destreset] at @s run tag @s remove destreset